FROM python:latest

ARG ENVIRONMENT_SETTINGS

WORKDIR /usr/src/app

COPY Pipfile Pipfile.lock ./

RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install $(test "$ENVIRONMENT_SETTINGS" = PRODUCTION || echo "--dev") --deploy --system --ignore-pipfile